;
; File generated by cc65 v 2.19 - Git b0e10e1
;
	.fopt		compiler,"cc65 v 2.19 - Git b0e10e1"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.import		_clrscr
	.import		_cputsxy
	.import		_textcolor
	.import		_bgcolor
	.import		_bordercolor
	.export		_qr2
	.export		_info
	.export		_main

.segment	"DATA"

_info:
	.addr	S0001
	.addr	S0002
	.addr	S0003
	.addr	S0004
	.addr	S0005
	.addr	S0006
	.addr	S0007
	.addr	S0008
	.addr	S0009
	.addr	S000A
	.addr	S000B
	.addr	S000C
	.addr	S000D
	.addr	S000E
	.addr	S000F
	.addr	S0010
	.addr	S0011
	.addr	S0012
	.addr	S0013
	.addr	S0014
	.addr	S0015
	.addr	S0016
	.addr	S0017

.segment	"RODATA"

_qr2:
	.byte	$7F
	.byte	$19
	.byte	$FC
	.byte	$41
	.byte	$09
	.byte	$04
	.byte	$5D
	.byte	$51
	.byte	$74
	.byte	$5D
	.byte	$35
	.byte	$74
	.byte	$5D
	.byte	$21
	.byte	$74
	.byte	$41
	.byte	$19
	.byte	$04
	.byte	$7F
	.byte	$55
	.byte	$FC
	.byte	$00
	.byte	$68
	.byte	$00
	.byte	$77
	.byte	$D7
	.byte	$10
	.byte	$18
	.byte	$36
	.byte	$44
	.byte	$4F
	.byte	$87
	.byte	$5C
	.byte	$1E
	.byte	$4E
	.byte	$48
	.byte	$29
	.byte	$EA
	.byte	$A0
	.byte	$00
	.byte	$5E
	.byte	$CC
	.byte	$7F
	.byte	$75
	.byte	$5C
	.byte	$41
	.byte	$7E
	.byte	$40
	.byte	$5D
	.byte	$54
	.byte	$A4
	.byte	$5D
	.byte	$15
	.byte	$E0
	.byte	$5D
	.byte	$64
	.byte	$54
	.byte	$41
	.byte	$6A
	.byte	$E8
	.byte	$7F
	.byte	$4E
	.byte	$2C
	.res	6,$00
S0018:
	.byte	$C9,$4E,$49,$54,$49,$41,$4C,$20,$D3,$45,$54,$55,$50,$20,$D7,$49
	.byte	$5A,$41,$52,$44,$00
S000F:
	.byte	$C1,$46,$54,$45,$52,$20,$43,$4F,$4E,$4E,$45,$43,$54,$49,$4E,$47
	.byte	$00
S0008:
	.byte	$54,$48,$45,$4E,$20,$4E,$41,$56,$49,$47,$41,$54,$45,$20,$54,$4F
	.byte	$00
S0005:
	.byte	$43,$4F,$4E,$4E,$45,$43,$54,$20,$57,$49,$54,$48,$20,$54,$48,$45
	.byte	$00
S0015:
	.byte	$4C,$4F,$43,$41,$4C,$20,$C9,$D0,$20,$41,$44,$44,$52,$45,$53,$53
	.byte	$00
S000A:
	.byte	$49,$4E,$20,$59,$4F,$55,$52,$20,$42,$52,$4F,$57,$53,$45,$52,$2C
	.byte	$00
S0009:
	.byte	$48,$54,$54,$50,$3A,$2F,$2F,$31,$30,$2E,$34,$32,$2E,$30,$2E,$31
	.byte	$00
S0004:
	.byte	$4F,$4E,$20,$59,$4F,$55,$52,$20,$44,$45,$56,$49,$43,$45,$2C,$00
S0016:
	.byte	$41,$53,$53,$49,$47,$4E,$45,$44,$20,$54,$4F,$20,$54,$48,$45,$00
S000B:
	.byte	$4F,$52,$20,$53,$43,$41,$4E,$20,$54,$48,$45,$20,$D1,$D2,$00
S0014:
	.byte	$50,$41,$47,$45,$20,$55,$53,$49,$4E,$47,$20,$54,$48,$45,$00
S0012:
	.byte	$59,$4F,$55,$20,$43,$41,$4E,$20,$41,$43,$43,$45,$53,$53,$00
S0011:
	.byte	$D7,$49,$2D,$C6,$49,$20,$4E,$45,$54,$57,$4F,$52,$4B,$2C,$00
S0003:
	.byte	$D7,$49,$2D,$C6,$49,$20,$4E,$45,$54,$57,$4F,$52,$4B,$00
S0007:
	.byte	$31,$32,$33,$34,$35,$36,$37,$38,$2C,$20,$41,$4E,$44,$00
S000C:
	.byte	$43,$4F,$44,$45,$20,$46,$4F,$52,$20,$41,$50,$50,$00
S0013:
	.byte	$54,$48,$45,$20,$53,$45,$54,$54,$49,$4E,$47,$53,$00
S0002:
	.byte	$C3,$36,$34,$C1,$C9,$2D,$D3,$45,$54,$55,$50,$00
S0010:
	.byte	$54,$4F,$20,$59,$4F,$55,$52,$20,$4F,$57,$4E,$00
S000D:
	.byte	$53,$45,$54,$54,$49,$4E,$47,$53,$2E,$00
S0006:
	.byte	$50,$41,$53,$53,$57,$4F,$52,$44,$00
S0001:
	.byte	$C6,$49,$4E,$44,$20,$54,$48,$45,$00
S0017:
	.byte	$44,$45,$56,$49,$43,$45,$2E,$00
S000E:
	.byte	$20,$00

; ---------------------------------------------------------------
; int __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

	jsr     decsp3
	lda     #$00
	jsr     _textcolor
	lda     #$0F
	jsr     _bordercolor
	lda     #$0F
	jsr     _bgcolor
	jsr     _clrscr
	lda     #$00
	ldy     #$02
L0026:	sta     (c_sp),y
	cmp     #$16
	jcs     L002E
	lda     #$00
	dey
L0025:	sta     (c_sp),y
	cmp     #$18
	jcs     L0004
	iny
	ldx     #$00
	lda     (c_sp),y
	jsr     mulax3
	sta     ptr1
	stx     ptr1+1
	dey
	lda     (c_sp),y
	lsr     a
	lsr     a
	lsr     a
	clc
	adc     ptr1
	ldx     ptr1+1
	bcc     L0022
	inx
L0022:	jsr     pushax
	lda     #$07
	jsr     pusha0
	ldy     #$05
	lda     (c_sp),y
	and     #$07
	jsr     tossuba0
	jsr     pushax
	ldy     #$06
	ldx     #$00
	lda     (c_sp),y
	jsr     incax1
	jsr     pushax
	lda     #$28
	jsr     tosmula0
	sta     ptr1
	stx     ptr1+1
	ldy     #$05
	lda     (c_sp),y
	clc
	adc     ptr1
	ldx     ptr1+1
	bcc     L0023
	inx
L0023:	sta     ptr1
	stx     ptr1+1
	lda     #$50
	clc
	adc     ptr1
	sta     sreg
	lda     #$04
	adc     ptr1+1
	sta     sreg+1
	ldy     #$03
	jsr     ldaxysp
	sta     ptr1
	txa
	clc
	adc     #>(_qr2)
	sta     ptr1+1
	ldy     #<(_qr2)
	ldx     #$00
	lda     (ptr1),y
	sta     ptr1
	lda     (c_sp,x)
	tay
	lda     ptr1
	jsr     asraxy
	and     #$01
	beq     L002C
	lda     #$A0
	jmp     L002D
L002C:	lda     #$20
L002D:	ldy     #$00
	sta     (sreg),y
	jsr     incsp4
	ldy     #$01
	clc
	tya
	adc     (c_sp),y
	jmp     L0025
L0004:	iny
	clc
	lda     #$01
	adc     (c_sp),y
	jmp     L0026
L002E:	tya
	jsr     _textcolor
	lda     #$0A
	jsr     pusha
	lda     #$00
	jsr     pusha
	lda     #<(S0018)
	ldx     #>(S0018)
	jsr     _cputsxy
	lda     #$0B
	jsr     _textcolor
	lda     #$00
	tay
L0027:	sta     (c_sp),y
	cmp     #$17
	bcs     L002F
	lda     #$18
	jsr     pusha
	ldy     #$01
	lda     (c_sp),y
	clc
	adc     #$02
	jsr     pusha
	ldy     #$02
	ldx     #$00
	lda     (c_sp),y
	asl     a
	bcc     L002B
	inx
	clc
L002B:	adc     #<(_info)
	tay
	txa
	adc     #>(_info)
	tax
	tya
	jsr     ldaxi
	jsr     _cputsxy
	ldy     #$00
	clc
	lda     #$01
	adc     (c_sp),y
	jmp     L0027
L002F:	tya
L0028:	sta     (c_sp),y
	cmp     #$0B
	bcs     L0030
	ldx     #$00
	lda     (c_sp),y
	ldy     #$90
	jsr     incaxy
	sta     ptr1
	stx     ptr1+1
	clc
	lda     #$D8
	adc     ptr1+1
	sta     ptr1+1
	lda     #$06
	ldy     #$00
	sta     (ptr1),y
	clc
	lda     #$01
	adc     (c_sp),y
	jmp     L0028
L0030:	tya
L0029:	sta     (c_sp),y
	cmp     #$08
	bcs     L0031
	ldx     #$01
	lda     #$58
	clc
	adc     (c_sp),y
	bcc     L0018
	inx
L0018:	sta     ptr1
	stx     ptr1+1
	clc
	lda     #$D8
	adc     ptr1+1
	sta     ptr1+1
	lda     #$06
	sta     (ptr1),y
	clc
	lda     #$01
	adc     (c_sp),y
	jmp     L0029
L0031:	lda     #$00
L002A:	sta     (c_sp),y
	cmp     #$10
L0032:	bcs     L0032
	ldx     #$01
	lda     #$A8
	clc
	adc     (c_sp),y
	bcc     L001D
	inx
L001D:	sta     ptr1
	stx     ptr1+1
	clc
	lda     #$D8
	adc     ptr1+1
	sta     ptr1+1
	lda     #$06
	sta     (ptr1),y
	clc
	lda     #$01
	adc     (c_sp),y
	jmp     L002A

.endproc

